name: lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eifinger/setup-rye@v4
        id: setup-rye
        with:
          enable-cache: true
          cache-prefix: "${{ runner.os }}-rye-${{ hashFiles('**/requirements.lock', '**/requirements-dev.lock') }}"
      - name: Install dependencies
        if: steps.setup-rye.outputs.cache-hit != 'true'
        run: |
          rye sync
      - name: Set up reviewdog
        uses: reviewdog/action-setup@v1
      - name: Run linter with reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          rye lint 2>&1 | reviewdog \
            -efm="%f:%l:%c: %t%*[^ ] %m" \
            -efm="%-G%.%#" \
            -name="rye-lint" \
            -reporter=github-check \
            -level=error \
            -fail-on-error \
            -filter-mode=nofilter
